/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as AuthPendingRouteImport } from './routes/auth-pending'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildListIdRouteImport } from './routes/build.$listId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPendingRoute = AuthPendingRouteImport.update({
  id: '/auth-pending',
  path: '/auth-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildListIdRoute = BuildListIdRouteImport.update({
  id: '/build/$listId',
  path: '/build/$listId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-pending': typeof AuthPendingRoute
  '/lists': typeof ListsRoute
  '/sign-in': typeof SignInRoute
  '/build/$listId': typeof BuildListIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-pending': typeof AuthPendingRoute
  '/lists': typeof ListsRoute
  '/sign-in': typeof SignInRoute
  '/build/$listId': typeof BuildListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-pending': typeof AuthPendingRoute
  '/lists': typeof ListsRoute
  '/sign-in': typeof SignInRoute
  '/build/$listId': typeof BuildListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth-pending' | '/lists' | '/sign-in' | '/build/$listId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth-pending' | '/lists' | '/sign-in' | '/build/$listId'
  id:
    | '__root__'
    | '/'
    | '/auth-pending'
    | '/lists'
    | '/sign-in'
    | '/build/$listId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthPendingRoute: typeof AuthPendingRoute
  ListsRoute: typeof ListsRoute
  SignInRoute: typeof SignInRoute
  BuildListIdRoute: typeof BuildListIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-pending': {
      id: '/auth-pending'
      path: '/auth-pending'
      fullPath: '/auth-pending'
      preLoaderRoute: typeof AuthPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/$listId': {
      id: '/build/$listId'
      path: '/build/$listId'
      fullPath: '/build/$listId'
      preLoaderRoute: typeof BuildListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthPendingRoute: AuthPendingRoute,
  ListsRoute: ListsRoute,
  SignInRoute: SignInRoute,
  BuildListIdRoute: BuildListIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
