// AUTO-GENERATED — do not edit by hand.
// Run `node tools/generate-types.js` to regenerate.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for war/source-json/*.json army data files. Intentionally loose (Phase 1): all existing files must validate. Will be tightened in S1.11 (require id) and S1.12 (require structured stat fields).
 */
export interface EpicArmyBuilderSourceJson {
  $schema?: string;
  metadata?: {
    army_name?: string;
    source_url?: string | null;
    page_title?: string;
    list_id?: string;
    status_note?: string;
    version?: string;
    version_note?: string;
    source_file?: string;
    display_name?: string;
    builder_source_file?: string;
    primary_pdf_source?: string;
    secondary_pdf_sources?: unknown;
    id?: string;
    name?: string;
    faction?: string;
    rulebook_url?: string;
    [k: string]: unknown;
  };
  army_stats?: {
    strategy_rating?: string | number;
    faction?: string;
    allegiance?: string;
    initiative_rating?: {
      entries?: {
        scope?: string;
        value?: string;
        [k: string]: unknown;
      }[];
      default?: unknown;
      exceptions?: unknown[];
      [k: string]: unknown;
    };
    faction_tags?: string[];
    [k: string]: unknown;
  };
  special_rules?: {
    name: string;
    text: string;
    id?: string;
    [k: string]: unknown;
  }[];
  /**
   * INFORMATIONAL ONLY — scraped from rulebook prose. The authoritative formation configuration for any ruleset lives in war/lists/<faction>_<ruleset>.json. Consumers building army lists or rendering formation UI MUST read from war/lists/*.json; source-json's formations[] captures the rulebook description (units_text, raw_text, etc.) for reference only. Per Decision C in docs/design/data-model.md.
   */
  formations?: {
    name: string;
    category?: string;
    entry_type?: string;
    cost?: string | null;
    units_text?: string | null;
    upgrades_or_options_text?: string | null;
    restrictions_or_notes?: string | null;
    raw_text?: string;
    parse_warnings?: string[];
    [k: string]: unknown;
  }[];
  profiles?: {
    name: string;
    type?: string;
    speed?: string;
    armour?: string;
    cc?: string;
    ff?: string;
    weapons?: {
      name: string;
      range?: string;
      firepower?: string;
      notes?: string[];
      [k: string]: unknown;
    }[];
    abilities?: string[];
    abilities_or_notes?: string[];
    id?: string;
    type_code?: string;
    armour_save?: number | null;
    cc_target?: number | null;
    ff_target?: number | null;
    speed_cm?: number | null;
    source_section?: string;
    parse_confidence?: string;
    parse_warnings?: string[];
    ambiguity_reasons?: string[];
    is_reference_or_ambiguous?: boolean;
    [k: string]: unknown;
  }[];
  army_notes?: (
    | string
    | {
        name?: string;
        text?: string;
        raw_text?: string;
        [k: string]: unknown;
      }
  )[];
  extraction_warnings?: unknown[];
  army_rules?: unknown[];
  rules?: unknown[];
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for war/lists/*.json army list files. Intentionally loose (Phase 1): all existing files must validate. Two files (EL_mymeara_NETEA.json, TEMPLATE.json) are known-invalid JSON and are excluded from validation.
 */
export interface EpicArmyBuilderArmyList {
  $schema?: string;
  id?: string;
  list_id?: string;
  faction_id?: string;
  ruleset?: string;
  version?: string;
  by?: string;
  notes?: string[] | string;
  sections: {
    id?: unknown;
    name: string;
    formations: {
      id?: number | string;
      string_id?: string;
      name: string;
      pts?: unknown;
      units?: unknown;
      upgrades?: unknown[];
      cost_pts?: unknown;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  upgrades?: {
    id: number | string;
    string_id?: string;
    name: string;
    pts?: unknown;
    cost_pts?: unknown;
    upgrades?: unknown[];
    [k: string]: unknown;
  }[];
  formationConstraints?: {
    [k: string]: unknown;
  }[];
  upgradeConstraints?: {
    [k: string]: unknown;
  }[];
  fixedFormations?: unknown[];
  [k: string]: unknown;
}
